name: Calculator Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with pytest
      working-directory: calc
      run: tox
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Setup git-semver
        run: GO111MODULE=on go get github.com/mdomke/git-semver/v6@v6.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=tag::$(git-semver | tr '+' '.')
      - name: Get Repo Owner
        id: get_repo_owner
        run: >
          echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} |
          tr '[:upper:]' '[:lower:]')
      - name: Debug variables
        run: |
          echo "repo_owner: ${{ steps.get_repo_owner.outputs.repo_owner }}"
          echo "tag: ${{ steps.get_tag.outputs.tag }}"
          echo "repo: ${{ github.repository }}"
          echo "git-describe: $(git describe --tags --always)"
          echo "go: $(go env)"
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ steps.get_repo_owner.outputs.repo_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Publish dev functions
        run: >
          OWNER="${{ steps.get_repo_owner.outputs.repo_owner }}"
          TAG="${{ steps.get_tag.outputs.tag }}"
          faas-cli publish
          --build-arg GO111MODULE=on
          --build-label org.opencontainers.image.source=https://github.com/${{ github.repository }}
